install:
	sudo pacman -S --noconfirm neofetch

config: config.conf logo.png
	rm -rf ~/.config/neofetch
	mkdir -p ~/.config/neofetch
	ln config.conf ~/.config/neofetch/
	ln logo.png ~/.config/neofetch/
