install:
	sudo pacman -S --noconfirm kitty termite

config:
	mkdir -p ~/.config/kitty ~/.config/termite
	rm -f ~/.config/kitty/kitty.conf ~/.config/termite/termite.conf
	ln kitty.conf ~/.config/kitty/
	ln termite.conf ~/.config/termite
